services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: uniselec-api
    container_name: uniselec-api
    restart: unless-stopped
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=uniselec
      - DB_USERNAME=root
      - DB_PASSWORD=root
    volumes:
      - .:/var/www/html
    ports:
      - "8083:80"
    networks:
      - uniselec-network

  db:
    image: mysql:8.0
    container_name: uniselec-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: uniselec
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - uniselec-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: uniselec-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8081:80"
    networks:
      - uniselec-network

networks:
  uniselec-network:
    driver: bridge

volumes:
  dbdata:
