name: Api - Production - Deploy
on:
  release:
    types: [published]

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest

    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: 📦 Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: 🛠️ Install Composer
      run: |
        curl -sS https://getcomposer.org/installer | php
        sudo mv composer.phar /usr/local/bin/composer
        composer --version

    - name: 📂 Install Dependencies
      run: composer install --no-dev --optimize-autoloader

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER_STAGING }}
        username: ${{ secrets.FTP_USERNAME_STAGING }}
        password: ${{ secrets.FTP_PASSWORD_STAGING }}